### ISSUE TITLE
Would you like to port over the chinese wiki into https://wiki.rwkv.com ?

### ISSUE THREAD

**Issue by PicoCreator** [RWKV-Wiki/RWKV-Wiki#1]
The main github repo is here : https://github.com/RWKV/RWKV-wiki/

The docs renderer is using vuepress2, which do support multi-lingual sites. So we could set it up there.

You should be able to find me on the RWKV discord with @picocreator , ping me on discord, and we can discuss further

PS: My Chinese is really really bad - and in the future as we onboard additional languages to the wiki - I would want more native speakers maintaining the respective languages wiki

**Comment by Sunbread** [comment]
okay
